//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "usuarios")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id: Uuid,
  pub nome: String,
  pub senha: String,
  #[sea_orm(unique)]
  pub email: String,
  pub created_at: DateTime,
  pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::tarefas::Entity")]
  Tarefas,
}

impl Related<super::tarefas::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Tarefas.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
